### ISSUE TITLE
docker build error - libcrypto and openssl-dev

### ISSUE THREAD

**Issue by Intecpsp** [OttPeterR/addon-babybuddy#11]
When trying to install the add-on just now, I got the below error:

`The command '/bin/bash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies build-base curl jpeg-dev libffi-dev libxml2-dev libxslt-dev postgresql-dev python3-dev zlib-dev' returned a non-zero code: 15`

**Comment by OttPeterR** [comment]
What hardware are you running?

**Comment by Intecpsp** [comment]
Currently running Home Assistant OS 8.2 in a VM on an M1 Mac. Does this project support aarch64?

**Comment by OttPeterR** [comment]
Hmm, I haven't dealt with an M1 yet but it does support aarch64. I personally run on aarch64 on an odroid n2+ and it's just fine but it's running under hassOS. I'll look into it more tonight and give an update here 👍

**Comment by peanutsguy** [comment]
Hi @OttPeterR! 

Same error here

"The command '/bin/bash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies build-base curl jpeg-dev libffi-dev libxml2-dev libxslt-dev postgresql-dev python3-dev zlib-dev' returned a non-zero code: 15"

Software & Hardware
Raspberry Pi 4 - Debian 11
Home Assistant 2022.7.0
Supervisor 2022.07.0
Frontend 20220706.0 - latest



Version | core-2022.7.0
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.10.0-15-arm64
CPU Architecture | aarch64
Timezone | America/Mexico_City
Configuration Directory | /config

**Comment by fvongierke** [comment]
Hi there. I'm having the same issue - getting the following error message:
![image](https://user-images.githubusercontent.com/99590368/178725784-602772a9-9388-4faa-9e8c-23131d33629f.png)

I'm running HA on the following hardware:
ODROID N2+ 4GB RAM
eMMC 5.1, 64 GB
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0
Docker version: 20.10.14

version: core-2022.7.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.10.5
os_name: Linux
os_version: 5.15.45
arch: aarch64
timezone: Europe/Berlin
config_dir: /config


Any help would be highly appreciated, baby is coming home from 3 weeks in the nicu in a couple of days (6+ weeks early).

**Comment by tinkerberlin** [comment]
Hi there. I'm having the same issue - getting the following error message:
![image](https://user-images.githubusercontent.com/99590368/178725784-602772a9-9388-4faa-9e8c-23131d33629f.png)

I'm running HA on the following hardware:
ODROID N2+ 4GB RAM
eMMC 5.1, 64 GB
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0
Docker version: 20.10.14

version: core-2022.7.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.10.5
os_name: Linux
os_version: 5.15.45
arch: aarch64
timezone: Europe/Berlin
config_dir: /config


Any help would be highly appreciated, baby is coming home from 3 weeks in the nicu in a couple of days (6+ weeks early).

**Comment by OttPeterR** [comment]
Took me some time but I finally got the error to happen on my local machine, its a dependency conflict. I'll work through this and pin them so hopefully this won't happen in the future. I'll try and get the fix out by tomorrow!

Also congrats @tinkerberlin! I hope all goes well!

**Comment by OttPeterR** [comment]
I've tried most things I know how to and I'm not sure what way I can fix the dependencies so I started a [thread](https://community.home-assistant.io/t/libcrypto-breaking-openssl-during-docker-build/439696) on the HA community website to see if anyone there can help take a look at it.

**Comment by tinkerberlin** [comment]
> Also congrats @tinkerberlin! I hope all goes well!

Thanks!

**Comment by tinkerberlin** [comment]
> I've tried most things I know how to and I'm not sure what way I can fix the dependencies so I started a [thread](https://community.home-assistant.io/t/libcrypto-breaking-openssl-during-docker-build/439696) on the HA community website to see if anyone there can help take a look at it.

Thanks! Do you know what is creating the dependency conflict? Is this due to a docker or HA update?

**Comment by OttPeterR** [comment]
the error is coming from [this step](https://github.com/OttPeterR/addon-babybuddy/blob/7f6ba16d7213e0f447bd5a50b4d8cd7fc8a6cde9/babybuddy/Dockerfile#L11) of the build process that's erroring, if you look in the HA logs for the supervisor (not core) you'll see this:

```
ERROR: unable to select packages:

  libcrypto1.1-1.1.1o-r0:
    breaks: openssl-dev-1.1.1q-r0[libcrypto1.1=1.1.1q-r0]
    satisfies: world[libcrypto1.1=1.1.1o-r0]
               ca-certificates-20211220-r0[so:libcrypto.so.1.1]
               python3-3.10.4-r0[so:libcrypto.so.1.1]
               libpq-14.4-r0[so:libcrypto.so.1.1]
               libcurl-7.83.1-r1[so:libcrypto.so.1.1]
               apk-tools-2.12.9-r3[so:libcrypto.so.1.1]
               libssl1.1-1.1.1o-r0[so:libcrypto.so.1.1]
  libssl1.1-1.1.1o-r0:
    breaks: openssl-dev-1.1.1q-r0[libssl1.1=1.1.1q-r0]
    satisfies: world[libssl1.1=1.1.1o-r0]
               python3-3.10.4-r0[so:libssl.so.1.1]
               libpq-14.4-r0[so:libssl.so.1.1]
               libcurl-7.83.1-r1[so:libssl.so.1.1]
               apk-tools-2.12.9-r3[so:libssl.so.1.1]
  postgresql14-dev-14.4-r0:
    breaks: build-dependencies-20220713.142129[postgresql-dev=14.4-r0]
  build-dependencies-20220713.142129:
    masked in: cache
    satisfies: world[build-dependencies=20220713.142129]
```

but where it gets strange is when I go into my currently running baby buddy addon (which is on the master version as of now), and I check the installed dependencies, the versions of openssl and libssl and libcrypto are all the same as the ones that are throwing those errors in the logs above

I believe the issue is that the dependencies aren't pinned (e.g. python3==3.10.4) and something updated somewhere that's causing that conflict, but I can't seem to find what it is. And when I try and pin dependencies to the versions in my currently running baby buddy, different but similar errors happen when some packages break others

**Comment by tinkerberlin** [comment]
OK.. I'm getting a headache just looking at that. Thank you for your work!

**Comment by OttPeterR** [comment]
Hey @tinkerberlin - give it a shot again, I think the maintainers of whichever package was having an issue resolved it, so it installed for me with no needed changes on my end!

**Comment by Intecpsp** [comment]
Still code 15 for me

**Comment by OttPeterR** [comment]
okay my bad, I accidentally re-used an already built container step from way before
but I think I got things ironed out and I pushed out a small patch, can you try again?

**Comment by tinkerberlin** [comment]
> okay my bad, I accidentally re-used an already built container step from way before but I think I got things ironed out and I pushed out a small patch, can you try again?

That seems to have fixed it. I got it installed and after changing the port I also got the web UI to open. 

Thanks!!!

Just one question: I still can't access BB through HA directly, right? That's the problem with the Ingress? Because when I click on the BB icon in the sidebar of HA, I get a 404 error.

Thanks!

**Comment by Intecpsp** [comment]
I was able to install as well and an seeing the 404 error using the sidebar in HA. But can access externally with my HA IP:Port.

**Comment by OttPeterR** [comment]
Okay then you're good to go as well, the sidebar doesn't work (see issue #2) so thats expected

I'll close this issue since I believe it's fixed now. Thanks everyone!
